### ISSUE TITLE
Warning/Error during compiling: format-truncation

### ISSUE THREAD

**Issue by saitam757** [RadeonOpenCompute/rocminfo#21]
Hi. On compiling _rocminfo_ I get the warning/error below.  Can switch off gcc flag for that but maybe of interest. Seems to be that a buffer size is too small.

System spec is:
Solus
g++ Version: 9.2.0

error in **rocminfo.cc:75:52** 
`‘hsa_status_t AcquireAgentInfo(hsa_agent_t, agent_info_t*)’:
/home/build/YPKG/root/rocminfo/build/rocminfo-roc-2.7.0/rocminfo.cc:75:52: error: ‘%#x’ directive output may be truncated writing between 1 and 10 bytes into a region of size 1 [-Werror=format-truncation=]
   75 |       snprintf(&(err_val[0]), sizeof(err_val[12]), "%#x", (uint32_t)err);  `

**Comment by justxi** [comment]
https://github.com/RadeonOpenCompute/rocminfo/pull/19 should fix it.

**Comment by saitam757** [comment]
@justxi Thank you.
