### ISSUE TITLE
`rocminfo` fails with HSA_STATUS_ERROR_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by guyru** [RadeonOpenCompute/rocminfo#27]
I've installed rocm-dev from the repository on Debian Buster. When I run `rocminfo` I get:
```
$ /opt/rocm/bin/rocminfo 
ROCk module is loaded
guyru is member of video group
hsa api call failure at: /data/jenkins_workspace/compute-rocm-rel-2.9/rocminfo/rocminfo.cc:1102
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.
```
I tried `strace`ing it to see what goes wrong and I think the problem might be in:
```
openat(AT_FDCWD, "/dev/kfd", O_RDWR|O_CLOEXEC) = -1 ENOMEM (Cannot allocate memory)
```

Dmesg gives the following error:
```
$ sudo dmesg | grep -e "amdgpu\|kfd"
[    2.712712] [drm] amdgpu kernel modesetting enabled.
[    2.720894] kfd kfd: Initialized module
[    2.721238] amdgpu 0000:02:00.0: kfd not supported on this ASIC
[    2.762143] amdgpu 0000:02:00.0: firmware: direct-loading firmware amdgpu/polaris12_mc.bin
[    2.762153] amdgpu 0000:02:00.0: VRAM: 2048M 0x000000F400000000 - 0x000000F47FFFFFFF (2048M used)
[    2.762153] amdgpu 0000:02:00.0: GART: 256M 0x0000000000000000 - 0x000000000FFFFFFF
[    2.762357] [drm] amdgpu: 2048M of VRAM memory ready
[    2.762358] [drm] amdgpu: 3072M of GTT memory ready.
```
Maybe the `kfd not supported on this ASIC` is the problem, but I don't know why.

I also tried the workaround in #20, but it doesn't seem to work in my case.

Some more details:
kernel: 4.19.0-6-amd64
Radeon RX 550X

**Comment by guyru** [comment]
I've tried upgrading to kernel 5.2.0. Now the `kfd` no longer complains about the ASIC but, does complain about PCIe atomics.
```
[    2.441403] kfd kfd: skipped device 1002:699f, PCI rejects atomics
```
However, my CPU is i7-8550U, which according to the installation page should be supported.

**Comment by fxkamd** [comment]
On some mother boards, PCIe v3 and atomics are not supported on all PCIe slots. Plugging the graphics card into a different slot may help.
