### ISSUE TITLE
RocmInfo SegFaults when first card is not supported

### ISSUE THREAD

**Issue by tuxd3v** [RadeonOpenCompute/rocminfo#7]
```
root@desktop:~# ls -ld /dev/kfd 
crw-rw----+ 1 root video 245, 0 Sep 18 13:08 /dev/kfd
root@desktop:~# dkms status
root@desktop:~# lsb_release -r
Release:	unstable
root@desktop:~# uname -a
Linux desktop 4.18.0-1-amd64 #1 SMP Debian 4.18.6-1 (2018-09-06) x86_64 GNU/Linux
root@desktop:~# id root
uid=0(root) gid=0(root) groups=0(root),44(video)
root@desktop:~# rocminfo
Segmentation fault
root@desktop:~# rocm-smi 
====================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD    MCLK OD
GPU[0] 		: WARNING: Empty SysFS value: power
GPU[0] 		: WARNING: Empty SysFS value: sclk
GPU[0] 		: WARNING: Empty SysFS value: sclk
GPU[0] 		: WARNING: Empty SysFS value: mclk
  0   8c      N/A      N/A      N/A      0%       auto      0%         0%       
  1   33c     38.9W    900Mhz   1000Mhz  16.86%   auto      0%         0%       
================================================================================
====================           End of ROCm SMI Log          ====================
```

MAYBE the problem is here:
'  // Acquire and display system information
  system_info_t sys_info;

  // This function will call HSA get_info functions to gather information
  // about the system.
  err = AcquireSystemInfo(&sys_info);'

The struct should contain only one card, the second one..

**Comment by jlgreathouse** [comment]
I think we'll need a bit more info here:

- What GPUs do you have installed?
- What distro and version are you running ("unstable" is a bit non-specific)
- Do you see GPU-using applications besides `rocminfo` work? (For example, `clinfo`, the `hipInfo` application you can build from `/opt/rocm/hip/samples/1_Utils/hipInfo/`)

**Comment by tuxd3v** [comment]
First of all,
Thanks in advance, for your time,

I am Running Debian Unstable :)

root@desktop:~# lspci|grep VGA
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Kaveri [Radeon R7 Graphics]
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480] (rev e7)

clinfo segfaults

I have so far, only installed this packages:
apt-get install rocm-opencl rocm-clang-ocl rocminfo rocm-smi rocm-utils  firmware-linux

firmware-linux, ( for amdgpu ).

I am trying to build the Helloworld Example, in the Rocm front page, my goals would be Torch Framwork:
"
root@desktop:~# g++ -I /opt/rocm/opencl/include/ ./HelloWorld.cpp -o HelloWorld -L/opt/rocm/opencl/lib/x86_64 -lOpenCL
./HelloWorld.cpp: In function ‘_cl_command_queue* CreateCommandQueue(cl_context, _cl_device_id**)’:
./HelloWorld.cpp:116:69: warning: ‘_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)’ is deprecated [-Wdeprecated-declarations]
     commandQueue = clCreateCommandQueue(context, devices[0], 0, NULL);
                                                                     ^
In file included from ./HelloWorld.cpp:23:
/opt/rocm/opencl/include/CL/cl.h:1364:1: note: declared here
 clCreateCommandQueue(cl_context                     /* context */,
 ^~~~~~~~~~~~~~~~~~~~
./HelloWorld.cpp:116:69: warning: ‘_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)’ is deprecated [-Wdeprecated-declarations]
     commandQueue = clCreateCommandQueue(context, devices[0], 0, NULL);
                                                                     ^
In file included from ./HelloWorld.cpp:23:
/opt/rocm/opencl/include/CL/cl.h:1364:1: note: declared here
 clCreateCommandQueue(cl_context                     /* context */,
 ^~~~~~~~~~~~~~~~~~~~
root@desktop:~# ./HelloWorld 
Segmentation fault
"
It also segfaults :(

strace rocminfo
---------------------
(...)
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/perf/iommu/max_concurrent", O_RDONLY) = -1 ENOENT (No such file or directory)
brk(0x1c6b000)                          = 0x1c6b000
close(5)                                = 0
statfs("/dev/shm/", {f_type=TMPFS_MAGIC, f_bsize=4096, f_blocks=1795629, f_bfree=1760160, f_bavail=1760160, f_files=1795629, f_ffree=1795457, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_NOSUID|ST_NODEV}) = 0
futex(0x7fcace910370, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "/dev/shm/sem.hsakmt_semaphore", O_RDWR|O_NOFOLLOW) = 5
fstat(5, {st_mode=S_IFREG|0644, st_size=32, ...}) = 0
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 5, 0) = 0x7fcacf0e8000
close(5)                                = 0
openat(AT_FDCWD, "/dev/shm/hsakmt_shared_mem", O_RDWR|O_CREAT|O_NOFOLLOW|O_CLOEXEC, 0666) = 5
ftruncate(5, 8)                         = 0
mmap(NULL, 8, PROT_READ|PROT_WRITE, MAP_SHARED, 5, 0) = 0x7fcacf0e0000
ioctl(3, AMDKFD_IOC_GET_VERSION, 0x7ffdd93bd3a0) = 0
openat(AT_FDCWD, "/proc/cpuinfo", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(6, "processor\t: 0\nvendor_id\t: Authen"..., 1024) = 1024
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/generation_id", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "1\n", 4096)                    = 2
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/system_properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "platform_oem 2314948418605039938"..., 4096) = 68
read(6, "", 4096)                       = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 7
fstat(7, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents(7, /* 3 entries */, 32768)     = 72
getdents(7, /* 0 entries */, 32768)     = 0
close(7)                                = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 6
read(6, "0-3\n", 8192)                  = 4
close(6)                                = 0
sched_getaffinity(0, 128, [0, 1, 2, 3]) = 64
sched_setaffinity(0, 128, [0])          = 0
sched_setaffinity(0, 128, [1])          = 0
sched_setaffinity(0, 128, [2])          = 0
sched_setaffinity(0, 128, [3])          = 0
sched_setaffinity(0, 128, [0, 1, 2, 3]) = 0
access("/sys/bus/pci", R_OK)            = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/gpu_id", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "8320\n", 4096)                 = 5
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "cpu_cores_count 4\nsimd_count 32\n"..., 4096) = 470
read(6, "", 4096)                       = 0
openat(AT_FDCWD, "/proc/cpuinfo", O_RDONLY) = 7
fstat(7, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(7, "processor\t: 0\nvendor_id\t: Authen"..., 1024) = 1024
read(7, "rs null_seg spectre_v1 spectre_v"..., 1024) = 1024
read(7, "id_msr tbm topoext perfctr_core "..., 1024) = 1024
read(7, "_tsc rep_good nopl nonstop_tsc c"..., 1024) = 1024
read(7, " 2\napicid\t\t: 19\ninitial apicid\t:"..., 1024) = 1024
read(7, "", 1024)                       = 0
close(7)                                = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/mem_banks/0/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "heap_type 0\nsize_in_bytes 858993"..., 4096) = 71
read(6, "", 4096)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/mem_banks/1/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "heap_type 0\nsize_in_bytes 858993"..., 4096) = 71
read(6, "", 4096)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/caches/0/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "processor_id_low 16\nlevel 1\nsize"..., 4096) = 632
read(6, "", 4096)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/caches/1/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "processor_id_low 16\nlevel 1\nsize"..., 4096) = 632
read(6, "", 4096)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/caches/2/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "processor_id_low 16\nlevel 2\nsize"..., 4096) = 635
read(6, "", 4096)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/caches/3/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "processor_id_low 17\nlevel 1\nsize"..., 4096) = 632
read(6, "", 4096)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/caches/4/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "processor_id_low 18\nlevel 1\nsize"..., 4096) = 632
read(6, "", 4096)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/caches/5/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "processor_id_low 18\nlevel 1\nsize"..., 4096) = 632
read(6, "", 4096)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/caches/6/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "processor_id_low 18\nlevel 2\nsize"..., 4096) = 635
read(6, "", 4096)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/nodes/0/caches/7/properties", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "processor_id_low 19\nlevel 1\nsize"..., 4096) = 632
read(6, "", 4096)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/sys/devices/virtual/kfd/kfd/topology/generation_id", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(6, "1\n", 4096)                    = 2
close(6)                                = 0
ioctl(3, AMDKFD_IOC_GET_CLOCK_COUNTERS, 0x7ffdd93bd2d0) = 0
ioctl(3, AMDKFD_IOC_GET_CLOCK_COUNTERS, 0x7ffdd93bd200) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x18} ---
+++ killed by SIGSEGV +++
Segmentation fault

Appart from Segfault at the end , I only see :+1: /sys/devices/virtual/kfd/kfd/topology/nodes/0/perf/iommu/max_concurrent", O_RDONLY) = -1 ENOENT (No such file or directory)

root@desktop:~# cat /sys/devices/virtual/kfd/kfd/topology/system_properties 
platform_oem 2314948418605039938
platform_id 4476225
platform_rev 1

I was thinking that it could be because of it cannot get values from first GPU, struct has pointers to NULL, but it was like guessing..
I would like to Configure the Scientific Torch Framework, that AMD is porting now,  :)

Thanks in Advance,
Regards

**Comment by jlgreathouse** [comment]
I don't think these applications should be segfaulting, so I'll try to configure a similar system tomorrow to run some tests.

That said, I can tell you that your current hardware setup will unfortunately not work with ROCm. As described in [our hardware requirements](https://github.com/RadeonOpenCompute/ROCm#supported-cpus), you will need a CPU that supports PCIe gen 3 with PCIe atomics in order to use your GPU within the ROCm software stack. The Kaveri-generation APUs from AMD have PCIe gen 3,[ but their PCIe controllers do not support PCIe atomics](https://github.com/RadeonOpenCompute/ROCm#not-supported).

As such, your system will not work with ROCm 1.9.

That said, I don't think things should segfault, so let me dig into that problem a bit more.

**Comment by tuxd3v** [comment]
We brought this machines at beginning of 2016,
My Chipset is the AMD A88X (Bolton-D4), I think it doesn't have pcie atomics, its a fm2+ socket
I think that in the past, maybe Rocm1.6 or so, Kaverys were supported

And we are locked on Fm2+,
Previously this machines were running CUDA, but with the Opensource effort by AMD, we wanted to check, and if ok, pass to AMD, to use Torch Framework.

The Idea was using iGPU for display, and dGPU for Compute.
So I brought 2 cards to check compatibility.

Ok, Thanks in Advance for your time.
Best Regards

**Comment by jlgreathouse** [comment]
Quick initial test on my home system: Ubuntu 16.04.5 LTS with rocm-dkms 1.9 and all its underlying packages installed. One GPU that is supported and one GPU that isn't. Unable to reproduce this problem so far.

@tuxd3v a few requests. Could you run the following and show me the output?
- `dmesg | grep kfd`
- If possible, could you run GDB on your HelloWorld application, and after the segfault run show me the output of `bt`?

**Comment by jlgreathouse** [comment]
Hi @tuxd3v 

I appreciate that Kaveri processors are not exactly old systems. The ROCm software stack may still work with the iGPU in your KV system, though this is not an officially supported hardware setup. What this means it that I can't offer any guarantees about whether or not it will work -- at this time we do not regularly test the integrated GPUs of APUs for ROCm compatibility. Instead, we have focused most of our efforts on building up support for discrete GPUs.

Our gfx8 discrete GPUs (Fiji, Polaris 10, Polaris 11) all require PCIe atomics from the host processor. We have made modifications to the firmware on our gfx9 discrete GPUs (Vega 10) so that this do not have this requirement. As such, a gfx9 GPU should work with your CPU. I run such a setup in one of my test systems.

However, with your current GPU, you would unfortunately need a CPU that supports PCIe atomics.

**Comment by tuxd3v** [comment]
Hello,

First of all, thanks for the support,
I had to travel to work on another country, in the mean time..

Ok, bellow in the dmesg, with kfd and amd keywords,
This is with the last upstream Mesa, from 20180925( if memory doesn't fail me ), that I upgraded today.

"dmesg|grep -E "kfd|amd"

[    0.000000] Linux version 4.18.0-1-amd64 (debian-kernel@lists.debian.org) (gcc version 7.3.0 (Debian 7.3.0-29)) #1 SMP Debian 4.18.8-1 (2018-09-18)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.18.0-1-amd64 root=UUID=5c82d6e4-b71e-4641-90d7-c0e13b09436a ro radeon.si_support=0 radeon.cik_support=0 radeon.modeset=0 amdgpu.si_support=1 amdgpu.cik_support=1 amdgpu.vm_fragment_size=9 amd_iommu=on amd_iommu=pt
[    0.000000] random: get_random_u32 called from bsp_init_amd+0x20d/0x2d0 with crng_init=0
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.18.0-1-amd64 root=UUID=5c82d6e4-b71e-4641-90d7-c0e13b09436a ro radeon.si_support=0 radeon.cik_support=0 radeon.modeset=0 amdgpu.si_support=1 amdgpu.cik_support=1 amdgpu.vm_fragment_size=9 amd_iommu=on amd_iommu=pt
[    0.781438] amd_uncore: AMD NB counters detected
[    0.781759] perf/amd_iommu: Detected AMD IOMMU #0 (2 banks, 4 counters/bank).
[    1.492245] usb usb1: Manufacturer: Linux 4.18.0-1-amd64 ehci_hcd
[    1.494980] usb usb2: Manufacturer: Linux 4.18.0-1-amd64 xhci-hcd
[    1.496665] usb usb3: Manufacturer: Linux 4.18.0-1-amd64 xhci-hcd
[    1.508432] usb usb4: Manufacturer: Linux 4.18.0-1-amd64 ehci_hcd
[    1.509685] usb usb5: Manufacturer: Linux 4.18.0-1-amd64 xhci-hcd
[    1.512757] usb usb7: Manufacturer: Linux 4.18.0-1-amd64 xhci-hcd
[    1.513678] usb usb8: Manufacturer: Linux 4.18.0-1-amd64 xhci-hcd
[    1.514326] usb usb9: Manufacturer: Linux 4.18.0-1-amd64 xhci-hcd
[    1.572279] usb usb6: Manufacturer: Linux 4.18.0-1-amd64 ohci_hcd
[    1.636282] usb usb10: Manufacturer: Linux 4.18.0-1-amd64 ohci_hcd
[    1.700356] usb usb11: Manufacturer: Linux 4.18.0-1-amd64 ohci_hcd
[   34.989320] [drm] amdgpu kernel modesetting enabled.
[   35.006522] kfd kfd: Initialized module
[   35.007737] amdgpu 0000:00:01.0: enabling device (0006 -> 0007)
[   35.056764] EDAC amd64: Node 0: DRAM ECC disabled.
[   35.056801] EDAC amd64: ECC disabled in the BIOS or no ECC capability, module will not load.
[   35.095765] amdgpu 0000:00:01.0: VRAM: 2048M 0x000000F400000000 - 0x000000F47FFFFFFF (2048M used)
[   35.095805] amdgpu 0000:00:01.0: GTT: 1024M 0x0000000000000000 - 0x000000003FFFFFFF
[   35.096562] [drm] amdgpu: 2048M of VRAM memory ready
[   35.096597] [drm] amdgpu: 3072M of GTT memory ready.
[   35.096966] [drm] amdgpu: dpm initialized
[   35.105009] amdgpu 0000:00:01.0: firmware: direct-loading firmware radeon/kaveri_pfp.bin
[   35.109745] amdgpu 0000:00:01.0: firmware: direct-loading firmware radeon/kaveri_me.bin
[   35.110960] amdgpu 0000:00:01.0: firmware: direct-loading firmware radeon/kaveri_ce.bin
[   35.112457] amdgpu 0000:00:01.0: firmware: direct-loading firmware radeon/kaveri_mec.bin
[   35.114589] amdgpu 0000:00:01.0: firmware: direct-loading firmware radeon/kaveri_mec2.bin
[   35.114797] amdgpu 0000:00:01.0: firmware: direct-loading firmware radeon/kaveri_rlc.bin
[   35.116992] amdgpu 0000:00:01.0: firmware: direct-loading firmware radeon/kaveri_sdma.bin
[   35.117269] amdgpu 0000:00:01.0: firmware: direct-loading firmware radeon/kaveri_sdma1.bin
[   35.118775] amdgpu 0000:00:01.0: firmware: direct-loading firmware radeon/kaveri_uvd.bin
[   35.120479] amdgpu 0000:00:01.0: firmware: direct-loading firmware radeon/kaveri_vce.bin
[   35.364946] kfd kfd: Allocated 3969056 bytes on gart
[   35.365104] kfd kfd: added device 1002:130f
[   35.565195] [drm] Initialized amdgpu 3.26.0 20150101 for 0000:00:01.0 on minor 0
[   35.566004] kfd kfd: skipped device 1002:67df, PCI rejects atomics
[   35.566379] amdgpu 0000:01:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff
[   35.567173] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_mc.bin
[   35.567220] amdgpu 0000:01:00.0: VRAM: 4096M 0x000000F400000000 - 0x000000F4FFFFFFFF (4096M used)
[   35.567259] amdgpu 0000:01:00.0: GTT: 256M 0x0000000000000000 - 0x000000000FFFFFFF
[   35.567391] [drm] amdgpu: 4096M of VRAM memory ready
[   35.567426] [drm] amdgpu: 4096M of GTT memory ready.
[   35.567920] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_pfp_2.bin
[   35.568123] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_me_2.bin
[   35.568296] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_ce_2.bin
[   35.568532] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_rlc.bin
[   35.569527] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_mec_2.bin
[   35.570578] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_mec2_2.bin
[   35.572905] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_sdma.bin
[   35.573068] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_sdma1.bin
[   35.574438] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_uvd.bin
[   35.575785] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_vce.bin
[   35.576956] amdgpu 0000:01:00.0: firmware: direct-loading firmware amdgpu/polaris10_k_smc.bin
[   35.820863] fbcon: amdgpudrmfb (fb0) is primary device
[   35.896326] amdgpu 0000:01:00.0: fb0: amdgpudrmfb frame buffer device
[   35.912876] [drm] Initialized amdgpu 3.26.0 20150101 for 0000:01:00.0 on minor 1
[   38.705877] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, trying to reset the ECPU!!!
[   39.718719] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, trying to reset the ECPU!!!
[   40.731099] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, trying to reset the ECPU!!!
[   41.743732] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, trying to reset the ECPU!!!
[   42.756345] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, trying to reset the ECPU!!!
[   43.768977] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, trying to reset the ECPU!!!
[   44.781462] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, trying to reset the ECPU!!!
[   45.794051] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, trying to reset the ECPU!!!
[   46.806612] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, trying to reset the ECPU!!!
[   47.819128] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, trying to reset the ECPU!!!
[   47.839041] [drm:vce_v2_0_start [amdgpu]] *ERROR* VCE not responding, giving up!!!
[   47.839085] [drm:amdgpu_device_ip_set_powergating_state [amdgpu]] *ERROR* set_powergating_state of IP block <vce_v2_0> failed -110
[   48.860230] [drm:amdgpu_vce_ring_test_ib [amdgpu]] *ERROR* amdgpu: IB test timed out.
[   48.860385] [drm:amdgpu_ib_ring_tests [amdgpu]] *ERROR* amdgpu: failed testing IB on ring 12 (-110).
[   48.860518] [drm:amdgpu_device_ip_late_init_func_handler [amdgpu]] *ERROR* ib ring test failed (-110).
[  125.679319] amdgpu 0000:01:00.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=io+mem
[  125.679325] amdgpu 0000:00:01.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=mem"

Kernel:
"uname -a
4.18.0-1-amd64 #1 SMP Debian 4.18.8-1 (2018-09-18) x86_64 GNU/Linux"

I don't get this error:
[   35.566379] amdgpu 0000:01:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff

I will try in the meantime to debug the HelloWorld example.

Thanks in Advance for your time.
Best Regards

**Comment by jlgreathouse** [comment]
Hi @tuxd3v 

I played around a bit with a similar setup in the meantime, and I've traced the issue back once again to system setup. Besides ROCm requiring PCIe atomics for your generation of GPU, ROCm does not (at this time) support APU+dGPU operation. In other word, we do not at this time support simultaneous iGPU + dGPU, and the problem you're running into is a known side effect of that.

This feature (APU+dGPU) is on our list of things we want to eventually support, but I cannot comment on when it would make it onto the roadmap.

**Comment by tuxd3v** [comment]
Hi @jlgreathouse,
Thanks you for your time.

Yes we were trying to get APUs for graphics, and a dGPU for Computation, in out QA Environments..
That was the idea, and it would be nice to have a APU+DGPU, with igpu(low power for Graphics), and dGPU for OpenCL( this makes more sense of course in QA Environments).

After reading your comment..I tried to disable iGPU, and I confirm what you discovered.

cat /sys/kernel/debug/vgaswitcheroo/switch
" 
0:DIS-Audio: :DynOff:0000:01:00.1
1:IGD: :Pwr:0000:00:01.0
2:DIS:+:Pwr:0000:01:00.0"

My system is muxless( I don't have a hardware switch, to switch between cards..), and when I try to disable unused iGPU, shell hangs forever..maybe because I don't own a hardware mux..

But I opened another one, and like you can see after:
"echo 'OFF' > /sys/kernel/debug/vgaswitcheroo/switch"

clinfo/rocminfo  doesn't segfault anymore:
clinfo
"
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted
"
rocminfo
" 
hsa api call failure at line 900, file: /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.9/rocminfo/rocminfo.cc. Call returned 4104
"
My Apologies, for this issue, that after all, had nothing to do with rocminfo.
Thank you very much

**Comment by jlgreathouse** [comment]
Hi @tuxd3v

Something to try — but that I haven’t tested. What about turning on ignore_crat for the amdkfd module? If you set this, the kfd will ignore the iGPU part of your APU and treat it like a dGPU. This might allow you to target the real dGPU while still using the iGPU display for graphics. 

I know that compute fails in the iGPU in this case, but it would be interesting to try for your use case.

**Comment by cfreehill** [comment]
Turns out issue was not rocminfo related.
